### ISSUE TITLE
Running on Cloudflare Workers

### ISSUE THREAD

**Issue by 0x62** [hybiscus-dev/nodejs-hybiscus-sdk#2]
I've been investigating Hybiscus to use for our internal reporting (currently using PDF.js), however our infrastructure is serverless on Cloudflare Workers, which is incompatible with `axios` as it relies on XHR which is not available (replaced with `fetch`).

Could you change requests to use `fetch` instead? You could also have an option when creating the client to override fetch instance so `cross-fetch` could be used in pure Node environments with the same API (or use by default based on the presence of global fetch).

**Comment by ismailuddin** [comment]
Hi there,

I think that sounds like a good option! Will be exploring this option in coming weeks!

**Comment by 0x62** [comment]
Had a deeper dive and realised I can swap out my own HTTP client and use `getDefinition()` instead so should be able to make it work regardless

**Comment by ismailuddin** [comment]
Good to hear that option can work fine for you as well! But thanks anyways for bringing this to our attention, as it would be better in general to be more flexible and support people in different environments!

**Comment by ismailuddin** [comment]
Thanks for your contributions!
