### ISSUE TITLE
nPages not passed correctly

### ISSUE THREAD

**Issue by 0x62** [hybiscus-dev/nodejs-hybiscus-sdk#3]
`1` is always returned by `getDefinition` regardless of value set when creating a report. I think this property should also be moved under `reportConfig` to match client structure with API.

https://github.com/hybiscus-dev/nodejs-hybiscus-sdk/blob/9e7b9cd83f5083487b67cb9fb80bd1c405383088/src/Report.ts#L86

**Comment by ismailuddin** [comment]
Thanks for picking up on this! PR has been merged!
